/*********************************************************************************************** 
** Author        : DengXiaoJun(邓小俊)
** Date          : 2023-08-21 10:49:58 +0800
** Description   : When I Has Time ,I Will Write Description Below:
** ModifyRecord1 :    
** ModifyRecord2 :    
** LastEditors   : DengXiaoJun(邓小俊)
** LastEditTime  : 2023-08-25 10:59:43 +0800
************************************************************************************************/ 
#include "DriverConfigMCU.h"
#include "BoardPortIn.h"
#include "BoardPortOut.h"

//主板输入初始化
//配置输入上拉还是下拉
const MCU_PIN_PULL boardPortInInitPullConfigArray[BOARD_PORT_IN_COUNT] = {
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_PH6_SEN1  
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_PH7_SEN2  
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_PH8_SEN3  
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_PH9_SEN4  
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_PG0_SEN5  
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_PG1_SEN6  
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_PE7_SEN7  
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_PE12_SEN8 
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_PF12_SEN9 
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_PF13_SEN10
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_PF14_SEN11
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_PF15_SEN12
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_PA3_SEN13 
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_PB0_SEN14 
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_PB1_SEN15 
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_PF11_SEN16
};

//板上IO初始化的上下拉配置
const MCU_PIN_PULL  boardPortOutInitPullConfigArray[BOARD_PORT_OUT_COUNT] = {
    MCU_PIN_PULL_PULLUP,//BOARD_OUT_MCU_PC4_ARM_CW1     
    MCU_PIN_PULL_PULLUP,//BOARD_OUT_MCU_PC5_ARM_CCW1    
    MCU_PIN_PULL_PULLUP,//BOARD_OUT_MCU_PA6_ARM_CW2     
    MCU_PIN_PULL_PULLUP,//BOARD_OUT_MCU_PA7_ARM_CCW2    
    MCU_PIN_PULL_PULLUP,//BOARD_OUT_MCU_PA4_ARM_CW3     
    MCU_PIN_PULL_PULLUP,//BOARD_OUT_MCU_PA5_ARM_CCW3    
    MCU_PIN_PULL_PULLUP,//BOARD_OUT_MCU_PE2_ARM_DCVALVE1
    MCU_PIN_PULL_PULLUP,//BOARD_OUT_MCU_PE3_ARM_DCVALVE2
    MCU_PIN_PULL_PULLUP,//BOARD_OUT_MCU_PG11_ARM_OUT1   
    MCU_PIN_PULL_PULLUP,//BOARD_OUT_MCU_PG12_ARM_OUT2   
    MCU_PIN_PULL_PULLUP,//BOARD_OUT_MCU_PG13_ARM_OUT3   
    MCU_PIN_PULL_PULLUP,//BOARD_OUT_MCU_PG14_ARM_OUT4   
};


//板上IO初始化的电平状态配置
const GPIO_PinState  boardPortOutInitLevelConfigArray[BOARD_PORT_OUT_COUNT] = {
    GPIO_PIN_RESET,//BOARD_OUT_MCU_PC4_ARM_CW1     
    GPIO_PIN_RESET,//BOARD_OUT_MCU_PC5_ARM_CCW1    
    GPIO_PIN_RESET,//BOARD_OUT_MCU_PA6_ARM_CW2     
    GPIO_PIN_RESET,//BOARD_OUT_MCU_PA7_ARM_CCW2    
    GPIO_PIN_RESET,//BOARD_OUT_MCU_PA4_ARM_CW3     
    GPIO_PIN_RESET,//BOARD_OUT_MCU_PA5_ARM_CCW3    
    GPIO_PIN_SET,//BOARD_OUT_MCU_PE2_ARM_DCVALVE1
    GPIO_PIN_SET,//BOARD_OUT_MCU_PE3_ARM_DCVALVE2
    GPIO_PIN_RESET,//BOARD_OUT_MCU_PG11_ARM_OUT1   
    GPIO_PIN_RESET,//BOARD_OUT_MCU_PG12_ARM_OUT2   
    GPIO_PIN_RESET,//BOARD_OUT_MCU_PG13_ARM_OUT3   
    GPIO_PIN_RESET,//BOARD_OUT_MCU_PG14_ARM_OUT4   
};





















