/*********************************************************************************************** 
** Author        : DengXiaoJun(邓小俊)
** Date          : 2023-08-21 10:49:58 +0800
** Description   : When I Has Time ,I Will Write Description Below:
** ModifyRecord1 :    
** ModifyRecord2 :    
** LastEditors   : DengXiaoJun(邓小俊)
** LastEditTime  : 2023-10-30 17:23:09 +0800
************************************************************************************************/ 
#include "DriverConfigMCU.h"
#include "BoardPortIn.h"
#include "BoardPortOut.h"



//主板输入初始化
//配置输入上拉还是下拉
const MCU_PIN_PULL boardPortInInitPullConfigArray[BOARD_PORT_IN_COUNT] = {
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_CPLD_NOP1 
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_CPLD_NOP2 
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_CPLD_NOP3 
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_CPLD_NOP4 
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_CPLD_NOP5 
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_CPLD_NOP6 
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_CPLD_NOP7 
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_CPLD_NOP8 
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_CPLD_NOP9 
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_CPLD_NOP10
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_CPLD_NOP11
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_CPLD_NOP12
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_CPLD_NOP13
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_ARM_SEN1_PI10             
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_ARM_SEN2_PI9              
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_ARM_SEN3_PC13             
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_ARM_SEN4_PI8              
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_ARM_SEN5_PE6              
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_ARM_SEN6_PE5              
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_ARM_SEN7_PE4              
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_ARM_SEN8_PE3              
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_ARM_SEN9_PE2              
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_ARM_SEN10_PI7             
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_ARM_SEN11_PI6             
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_ARM_SEN12_PI5             
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_ARM_SEN13_PI4             
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_ARM_SEN14_PB9             
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_ARM_SEN15_PB8             
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_ARM_SEN16_PB7             
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_SLAVE_ARM_SEN1_PH12       
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_SLAVE_ARM_SEN2_PH11       
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_SLAVE_ARM_SEN3_PH10       
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_SLAVE_ARM_SEN4_PH9        
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_SLAVE_ARM_SEN5_PH8        
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_SLAVE_ARM_SEN6_PH7        
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_SLAVE_ARM_SEN7_PH6        
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_SLAVE_ARM_SEN8_PB11       
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_SLAVE_ARM_SEN9_PB10       
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_SLAVE_ARM_SEN10_PC0       
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_SLAVE_ARM_SEN11_PC1       
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_SLAVE_ARM_SEN12_PC2       
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_SLAVE_ARM_SEN13_PC3       
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_SLAVE_ARM_SEN14_PB1       
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_SLAVE_ARM_SEN15_PB0       
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_SLAVE_ARM_SEN16_PC5       
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_FRUBBISH1_PH15            
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_FRUBBISH2_PH14            
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_FRUBBISH3_PH13            
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_FRUBBISH4_PC9             
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_FRUBBISH_OVER1_PI0        
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_FRUBBISH_OVER2_PI1        
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_PR1_ARM1_PG14             
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_PR1_ARM2_PG13             
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_PR2_ARM1_PG11             
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_PR2_ARM2_PG10             
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_YM1_ARM1_PB6              
    MCU_PIN_PULL_PULLDOWN,//BOARD_PORT_IN_YM1_ARM2_PB5              
};


//板上IO初始化的电平状态配置
const GPIO_PinState  boardPortOutInitLevelConfigArray[BOARD_PORT_OUT_COUNT] = {
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC1     
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC2     
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC3     
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC4     
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC5     
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC6     
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC7     
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC8     
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC9     
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC10    
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC11    
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC12    
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC13    
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC14    
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC15    
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC16    
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC17    
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC18    
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC19    
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC20    
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC21    
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC22    
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC23    
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC24    
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC25    
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC26    
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC27    
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC28    
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC29    
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC30    
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC31    
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC32    
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC33    
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC34    
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC35    
    GPIO_PIN_SET,//BOARD_PORT_OUT_CPLD_CDC36    
    GPIO_PIN_SET,//BOARD_PORT_OUT_SLAVE_SEN17_PC4              
    GPIO_PIN_SET,//BOARD_PORT_OUT_SLAVE_SEN18_PA7              
    GPIO_PIN_SET,//BOARD_PORT_OUT_SLAVE_SEN19_PA6              
    GPIO_PIN_SET,//BOARD_PORT_OUT_SLAVE_SEN20_PA5              
    GPIO_PIN_SET,//BOARD_PORT_OUT_SLAVE_SEN21_PA4              
    GPIO_PIN_SET,//BOARD_PORT_OUT_SLAVE_SEN22_PA3              
    GPIO_PIN_SET,//BOARD_PORT_OUT_SLAVE_SEN23_PF8              
    GPIO_PIN_SET,//BOARD_PORT_OUT_SLAVE_SEN24_PF9              
    GPIO_PIN_SET,//BOARD_PORT_OUT_SLAVE_SEN25_PF10             
    GPIO_PIN_SET,//BOARD_PORT_OUT_SLAVE_SEN26_PH3              
    GPIO_PIN_SET,//BOARD_PORT_OUT_SLAVE_SEN27_PH2              
    GPIO_PIN_SET,//BOARD_PORT_OUT_SLAVE_SEN28_PA2              
    GPIO_PIN_SET,//BOARD_PORT_OUT_SLAVE_DC1_VAVLE_PC8          
    GPIO_PIN_SET,//BOARD_PORT_OUT_SLAVE_DC2_RUBBISH_MOTOR1_PG9 
    GPIO_PIN_SET,//BOARD_PORT_OUT_SLAVE_DC3_RUBBISH_MOTOR2_PD6 
    GPIO_PIN_SET,//BOARD_PORT_OUT_SLAVE_DC4_RUBBISH_MOTOR3_PI3 
    GPIO_PIN_SET,//BOARD_PORT_OUT_SLAVE_DC5_RUBBISH_MOTOR4_PI2 
    GPIO_PIN_SET,//BOARD_PORT_OUT_YM1_ARM3_PB4                 
    GPIO_PIN_SET,//BOARD_PORT_OUT_YM1_ARM4_PG15                
};


//板上IO初始化的上下拉配置
const MCU_PIN_PULL  boardPortOutInitPullConfigArray[BOARD_PORT_OUT_COUNT] = {
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC1     
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC2     
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC3     
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC4     
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC5     
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC6     
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC7     
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC8     
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC9     
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC10    
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC11    
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC12    
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC13    
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC14    
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC15    
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC16    
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC17    
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC18    
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC19    
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC20    
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC21    
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC22    
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC23    
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC24    
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC25    
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC26    
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC27    
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC28    
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC29    
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC30    
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC31    
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC32    
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC33    
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC34    
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC35    
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_CPLD_CDC36    
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_SLAVE_SEN17_PC4              
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_SLAVE_SEN18_PA7              
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_SLAVE_SEN19_PA6              
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_SLAVE_SEN20_PA5              
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_SLAVE_SEN21_PA4              
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_SLAVE_SEN22_PA3              
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_SLAVE_SEN23_PF8              
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_SLAVE_SEN24_PF9              
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_SLAVE_SEN25_PF10             
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_SLAVE_SEN26_PH3              
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_SLAVE_SEN27_PH2              
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_SLAVE_SEN28_PA2              
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_SLAVE_DC1_VAVLE_PC8          
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_SLAVE_DC2_RUBBISH_MOTOR1_PG9 
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_SLAVE_DC3_RUBBISH_MOTOR2_PD6 
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_SLAVE_DC4_RUBBISH_MOTOR3_PI3 
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_SLAVE_DC5_RUBBISH_MOTOR4_PI2 
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_YM1_ARM3_PB4                 
    MCU_PIN_PULL_PULLUP,//BOARD_PORT_OUT_YM1_ARM4_PG15                
};

















