/************************************************************************ 
 ** Author       : 邓小俊
 ** Date         : 2024-01-29 11:51:45
 ** Description  : When I Has Free Time ,I Will Write Description Below.
 ** description  : 
 ** LastEditors  : 邓小俊
 ** LastEditTime : 2024-01-29 13:08:48
 ** Email: xiaojun.deng@aliyun.com
 ** Copyright (c) 2024 by 公司名称, All Rights Reserved. 
 ************************************************************************/
#include "MCU_FMC_Port.h"
#include "MCU_PIN.h"

//初始化标志,防止反复初始化
static uint8_t mcu_FmcPinInitFlag = 0;

//板上FMC端口初始化
void MCU_FMC_PortInit(void)
{
    //防止重复初始化
    if(mcu_FmcPinInitFlag != 0)
    {
        return;
    }
    mcu_FmcPinInitFlag = 1;
	__HAL_RCC_FMC_CLK_ENABLE();
    //控制信号
    //PC0   ------> FMC_SDNWE 
    MCU_PinInit(MCU_PIN_C_0,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PH2  <-> FMC_SDCKE0
    MCU_PinInit(MCU_PIN_H_2,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PH3  <-> FMC_SDNE0
    MCU_PinInit(MCU_PIN_H_3,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PF11 <-> FMC_SDNRAS
    MCU_PinInit(MCU_PIN_F_11,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PH6  <-> FMC_SDNE1
    MCU_PinInit(MCU_PIN_H_6,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PH7  <-> FMC_SDCKE1
    MCU_PinInit(MCU_PIN_H_7,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PG4  <-> FMC_BA0
    MCU_PinInit(MCU_PIN_G_4,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PG5  <-> FMC_BA1
    MCU_PinInit(MCU_PIN_G_5,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PG8  <-> FMC_SDCLK
    MCU_PinInit(MCU_PIN_G_8,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PG15 <-> FMC_SDNCAS
    MCU_PinInit(MCU_PIN_G_15,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PE0  <-> FMC_NBL0
    MCU_PinInit(MCU_PIN_E_0,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PE1  <-> FMC_NBL1
    MCU_PinInit(MCU_PIN_E_1,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);

    //地址信号
    //PF0 <-> FMC_A0 
    MCU_PinInit(MCU_PIN_F_0,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PF1 <-> FMC_A1 
    MCU_PinInit(MCU_PIN_F_1,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PF2 <-> FMC_A2 
    MCU_PinInit(MCU_PIN_F_2,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PF3 <-> FMC_A3
    MCU_PinInit(MCU_PIN_F_3,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PF4 <-> FMC_A4 
    MCU_PinInit(MCU_PIN_F_4,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PF5 <-> FMC_A5 
    MCU_PinInit(MCU_PIN_F_5,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PF12 <-> FMC_A6 
    MCU_PinInit(MCU_PIN_F_12,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PF13 <-> FMC_A7 
    MCU_PinInit(MCU_PIN_F_13,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PF14 <-> FMC_A8 
    MCU_PinInit(MCU_PIN_F_14,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PF15 <-> FMC_A9
    MCU_PinInit(MCU_PIN_F_15,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PG0 <-> FMC_A10 
    MCU_PinInit(MCU_PIN_G_0,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PG1 <-> FMC_A11   
    MCU_PinInit(MCU_PIN_G_1,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PG2 <-> FMC_A12 
    MCU_PinInit(MCU_PIN_G_2,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);

    //数据信号
    //PD14 <-> FMC_D0   
    MCU_PinInit(MCU_PIN_D_14,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PD15 <-> FMC_D1
    MCU_PinInit(MCU_PIN_D_15,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PD0 <-> FMC_D2 
    MCU_PinInit(MCU_PIN_D_0,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PD1 <-> FMC_D3
    MCU_PinInit(MCU_PIN_D_1,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PE7 <-> FMC_D4  
    MCU_PinInit(MCU_PIN_E_7,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PE8 <-> FMC_D5 
    MCU_PinInit(MCU_PIN_E_8,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PE9 <-> FMC_D6 
    MCU_PinInit(MCU_PIN_E_9,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PE10 <-> FMC_D7 
    MCU_PinInit(MCU_PIN_E_10,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PE11 <-> FMC_D8
    MCU_PinInit(MCU_PIN_E_11,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PE12 <-> FMC_D9
    MCU_PinInit(MCU_PIN_E_12,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PE13 <-> FMC_D10
    MCU_PinInit(MCU_PIN_E_13,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PE14 <-> FMC_D11 
    MCU_PinInit(MCU_PIN_E_14,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PE15 <-> FMC_D12  
    MCU_PinInit(MCU_PIN_E_15,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PD8  <-> FMC_D13
    MCU_PinInit(MCU_PIN_D_8,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PD9  <-> FMC_D14
    MCU_PinInit(MCU_PIN_D_9,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
    //PD10 <-> FMC_D15
    MCU_PinInit(MCU_PIN_D_10,MCU_PIN_MODE_AF_PP,MCU_PIN_PULL_PULLUP,MCU_PIN_SPEED_FREQ_VERY_HIGH,GPIO_AF12_FMC);
}


//板上FMC端口初始化
void MCU_FMC_PortDeInit(void)
{
    mcu_FmcPinInitFlag = 0;
    //模块复位
    __HAL_RCC_FMC_FORCE_RESET();
    __HAL_RCC_FMC_RELEASE_RESET();
    /* 禁止FMC时钟 */
	__HAL_RCC_FMC_CLK_DISABLE();

    //控制信号
    //PC0   ------> FMC_SDNWE 
    MCU_PinDeInit(MCU_PIN_C_0);
    //PH2  <-> FMC_SDCKE0
    MCU_PinDeInit(MCU_PIN_H_2);
    //PH3  <-> FMC_SDNE0
    MCU_PinDeInit(MCU_PIN_H_3);
    //PF11 <-> FMC_SDNRAS
    MCU_PinDeInit(MCU_PIN_F_11);
    //PH6  <-> FMC_SDNE1
    MCU_PinDeInit(MCU_PIN_H_6);
    //PH7  <-> FMC_SDCKE1
    MCU_PinDeInit(MCU_PIN_H_7);
    //PG4  <-> FMC_BA0
    MCU_PinDeInit(MCU_PIN_G_4);
    //PG5  <-> FMC_BA1
    MCU_PinDeInit(MCU_PIN_G_5);
    //PG8  <-> FMC_SDCLK
    MCU_PinDeInit(MCU_PIN_G_8);
    //PG15 <-> FMC_SDNCAS
    MCU_PinDeInit(MCU_PIN_G_15);
    //PE0  <-> FMC_NBL0
    MCU_PinDeInit(MCU_PIN_E_0);
    //PE1  <-> FMC_NBL1
    MCU_PinDeInit(MCU_PIN_E_1);

    //地址信号
    //PF0 <-> FMC_A0 
    MCU_PinDeInit(MCU_PIN_F_0);
    //PF1 <-> FMC_A1 
    MCU_PinDeInit(MCU_PIN_F_1);
    //PF2 <-> FMC_A2 
    MCU_PinDeInit(MCU_PIN_F_2);
    //PF3 <-> FMC_A3
    MCU_PinDeInit(MCU_PIN_F_3);
    //PF4 <-> FMC_A4 
    MCU_PinDeInit(MCU_PIN_F_4);
    //PF5 <-> FMC_A5 
    MCU_PinDeInit(MCU_PIN_F_5);
    //PF12 <-> FMC_A6 
    MCU_PinDeInit(MCU_PIN_F_12);
    //PF13 <-> FMC_A7 
    MCU_PinDeInit(MCU_PIN_F_13);
    //PF14 <-> FMC_A8 
    MCU_PinDeInit(MCU_PIN_F_14);
    //PF15 <-> FMC_A9
    MCU_PinDeInit(MCU_PIN_F_15);
    //PG0 <-> FMC_A10 
    MCU_PinDeInit(MCU_PIN_G_0);
    //PG1 <-> FMC_A11   
    MCU_PinDeInit(MCU_PIN_G_1);
    //PG2 <-> FMC_A12 
    MCU_PinDeInit(MCU_PIN_G_2);

    //数据信号
    //PD14 <-> FMC_D0   
    MCU_PinDeInit(MCU_PIN_D_14);
    //PD15 <-> FMC_D1
    MCU_PinDeInit(MCU_PIN_D_15);
    //PD0 <-> FMC_D2 
    MCU_PinDeInit(MCU_PIN_D_0);
    //PD1 <-> FMC_D3
    MCU_PinDeInit(MCU_PIN_D_1);
    //PE7 <-> FMC_D4  
    MCU_PinDeInit(MCU_PIN_E_7);
    //PE8 <-> FMC_D5 
    MCU_PinDeInit(MCU_PIN_E_8);
    //PE9 <-> FMC_D6 
    MCU_PinDeInit(MCU_PIN_E_9);
    //PE10 <-> FMC_D7 
    MCU_PinDeInit(MCU_PIN_E_10);
    //PE11 <-> FMC_D8
    MCU_PinDeInit(MCU_PIN_E_11);
    //PE12 <-> FMC_D9
    MCU_PinDeInit(MCU_PIN_E_12);
    //PE13 <-> FMC_D10
    MCU_PinDeInit(MCU_PIN_E_13);
    //PE14 <-> FMC_D11 
    MCU_PinDeInit(MCU_PIN_E_14);
    //PE15 <-> FMC_D12  
    MCU_PinDeInit(MCU_PIN_E_15);
    //PD8  <-> FMC_D13
    MCU_PinDeInit(MCU_PIN_D_8);
    //PD9  <-> FMC_D14
    MCU_PinDeInit(MCU_PIN_D_9);
    //PD10 <-> FMC_D15
    MCU_PinDeInit(MCU_PIN_D_10);
}



