/*********************************************************************************************** 
** Author        : DengXiaoJun(邓小俊)
** Date          : 2023-08-29 14:07:30 +0800
** Description   : When I Has Time ,I Will Write Description Below:
** ModifyRecord1 :    
** ModifyRecord2 :    
** LastEditors   : DengXiaoJun(邓小俊)
** LastEditTime  : 2023-09-22 10:08:11 +0800
************************************************************************************************/ 
#ifndef __SYS_PARAM_H_
#define __SYS_PARAM_H_
#include "SysParamDefault.h"

//主序号
typedef enum INDEX_MAIN_SYS_PARAM
{
    INDEX_MAIN_SYS_PARAM_LATERALLY_MOTOR    = 0X00,//直线电机坐标参数集合
    INDEX_MAIN_SYS_PARAM_UPDOWN_MOTOR       = 0X01,//升降电机坐标参数集合
    INDEX_MAIN_SYS_PARAM_ROD_MOTOR          = 0X02,//顶杆电机坐标参数集合
    INDEX_MAIN_SYS_PARAM_BELT_MOTOR         = 0X03,//皮带电机坐标参数集合
    INDEX_MAIN_SYS_PARAM_URIL               = 0X04,//辅助参数
}INDEX_MAIN_SYS_PARAM;

//直线电机坐标参数集合
typedef enum INDEX_SUB_PARAM_LATERALLY_MOTOR
{
    INDEX_SUB_PARAM_LATERALLY_MOTOR_RESET_CORRECT       = 0X00,//复位修正 
    INDEX_SUB_PARAM_LATERALLY_MOTOR_DIR_SWITCH_CORRECT  = 0X01,//换向修正 
    INDEX_SUB_PARAM_LATERALLY_MOTOR_IDLE_POS            = 0X02,//空闲位置 
    INDEX_SUB_PARAM_LATERALLY_MOTOR_RACK_STORE1_POS     = 0X03,//试管架仓1号位置 
    INDEX_SUB_PARAM_LATERALLY_MOTOR_RACK_STORE2_POS     = 0X04,//试管架仓2号位置 
    INDEX_SUB_PARAM_LATERALLY_MOTOR_RACK_STORE3_POS     = 0X05,//试管架仓3号位置 
    INDEX_SUB_PARAM_LATERALLY_MOTOR_RACK_STORE4_POS     = 0X06,//试管架仓4号位置 
    INDEX_SUB_PARAM_LATERALLY_MOTOR_RACK_STORE5_POS     = 0X07,//试管架仓5号位置 
    INDEX_SUB_PARAM_LATERALLY_MOTOR_RACK_STORE6_POS     = 0X08,//试管架仓6号位置 
    INDEX_SUB_PARAM_LATERALLY_MOTOR_RACK_STORE7_POS     = 0X09,//试管架仓7号位置 
    INDEX_SUB_PARAM_LATERALLY_MOTOR_RACK_STORE8_POS     = 0X0A,//试管架仓8号位置 
    INDEX_SUB_PARAM_LATERALLY_MOTOR_RACK_STORE9_POS     = 0X0B,//试管架仓9号位置 
    INDEX_SUB_PARAM_LATERALLY_MOTOR_RACK_STORE10_POS    = 0X0C,//试管架仓10号位置 
    INDEX_SUB_PARAM_LATERALLY_MOTOR_RACK_STORE11_POS    = 0X0D,//试管架仓11号位置 
    INDEX_SUB_PARAM_LATERALLY_MOTOR_RACK_STORE12_POS    = 0X0E,//试管架仓12号位置 
    INDEX_SUB_PARAM_LATERALLY_MOTOR_RACK_STORE13_POS    = 0X0F,//试管架仓13号位置 
    INDEX_SUB_PARAM_LATERALLY_MOTOR_RACK_STORE14_POS    = 0X10,//试管架仓14号位置 
    INDEX_SUB_PARAM_LATERALLY_MOTOR_RACK_STORE15_POS    = 0X11,//试管架仓15号位置 
    INDEX_SUB_PARAM_LATERALLY_MOTOR_RACK_STORE16_POS    = 0X12,//试管架仓16号位置 
    INDEX_SUB_PARAM_LATERALLY_MOTOR_RACK_STORE17_POS    = 0X13,//试管架仓17号位置 
    INDEX_SUB_PARAM_LATERALLY_MOTOR_RACK_STORE18_POS    = 0X14,//试管架仓18号位置 
    INDEX_SUB_PARAM_LATERALLY_MOTOR_RACK_STORE19_POS    = 0X15,//试管架仓19号位置 
    INDEX_SUB_PARAM_LATERALLY_MOTOR_RACK_STORE20_POS    = 0X16,//试管架仓20号位置 
    INDEX_SUB_PARAM_LATERALLY_MOTOR_RACK_STORE21_POS    = 0X17,//试管架仓21号位置 
    INDEX_SUB_PARAM_LATERALLY_MOTOR_RACK_STORE22_POS    = 0X18,//试管架仓22号位置 
    INDEX_SUB_PARAM_LATERALLY_MOTOR_RACK_STORE23_POS    = 0X19,//试管架仓23号位置 
    INDEX_SUB_PARAM_LATERALLY_MOTOR_C21_INTER_POS       = 0X1A,//C21接口位置
}INDEX_SUB_APP_RAIL_NODE_ENTRY_PARAM;

//升降电机坐标参数集合
typedef enum INDEX_SUB_PARAM_UPDOWN_MOTOR
{
    INDEX_SUB_PARAM_UPDOWN_MOTOR_RESET_CORRECT              = 0X00,//复位修正
    INDEX_SUB_PARAM_UPDOWN_MOTOR_DIR_SWITCH_CORRECT         = 0X01,//换向修正
    INDEX_SUB_PARAM_UPDOWN_MOTOR_IDLE_POS                   = 0X02,//空闲位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_LOAD_RACK_STORE1_POS       = 0X03,//试管架仓1装载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_UNLOAD_RACK_STORE1_POS     = 0X04,//试管架仓1卸载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_LOAD_RACK_STORE2_POS       = 0X05,//试管架仓2装载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_UNLOAD_RACK_STORE2_POS     = 0X06,//试管架仓2卸载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_LOAD_RACK_STORE3_POS       = 0X07,//试管架仓3装载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_UNLOAD_RACK_STORE3_POS     = 0X08,//试管架仓3卸载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_LOAD_RACK_STORE4_POS       = 0X09,//试管架仓4装载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_UNLOAD_RACK_STORE4_POS     = 0X0A,//试管架仓4卸载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_LOAD_RACK_STORE5_POS       = 0X0B,//试管架仓5装载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_UNLOAD_RACK_STORE5_POS     = 0X0C,//试管架仓5卸载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_LOAD_RACK_STORE6_POS       = 0X0D,//试管架仓6装载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_UNLOAD_RACK_STORE6_POS     = 0X0E,//试管架仓6卸载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_LOAD_RACK_STORE7_POS       = 0X0F,//试管架仓7装载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_UNLOAD_RACK_STORE7_POS     = 0X10,//试管架仓7卸载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_LOAD_RACK_STORE8_POS       = 0X11,//试管架仓8装载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_UNLOAD_RACK_STORE8_POS     = 0X12,//试管架仓8卸载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_LOAD_RACK_STORE9_POS       = 0X13,//试管架仓9装载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_UNLOAD_RACK_STORE9_POS     = 0X14,//试管架仓9卸载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_LOAD_RACK_STORE10_POS      = 0X15,//试管架仓10装载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_UNLOAD_RACK_STORE10_POS    = 0X16,//试管架仓10卸载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_LOAD_RACK_STORE11_POS      = 0X17,//试管架仓11装载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_UNLOAD_RACK_STORE11_POS    = 0X18,//试管架仓11卸载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_LOAD_RACK_STORE12_POS      = 0X19,//试管架仓12装载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_UNLOAD_RACK_STORE12_POS    = 0X1A,//试管架仓12卸载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_LOAD_RACK_STORE13_POS      = 0X1B,//试管架仓13装载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_UNLOAD_RACK_STORE13_POS    = 0X1C,//试管架仓13卸载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_LOAD_RACK_STORE14_POS      = 0X1D,//试管架仓14装载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_UNLOAD_RACK_STORE14_POS    = 0X1E,//试管架仓14卸载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_LOAD_RACK_STORE15_POS      = 0X1F,//试管架仓15装载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_UNLOAD_RACK_STORE15_POS    = 0X20,//试管架仓15卸载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_LOAD_RACK_STORE16_POS      = 0X21,//试管架仓16装载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_UNLOAD_RACK_STORE16_POS    = 0X22,//试管架仓16卸载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_LOAD_RACK_STORE17_POS      = 0X23,//试管架仓17装载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_UNLOAD_RACK_STORE17_POS    = 0X24,//试管架仓17卸载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_LOAD_RACK_STORE18_POS      = 0X25,//试管架仓18装载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_UNLOAD_RACK_STORE18_POS    = 0X26,//试管架仓18卸载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_LOAD_RACK_STORE19_POS      = 0X27,//试管架仓19装载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_UNLOAD_RACK_STORE19_POS    = 0X28,//试管架仓19卸载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_LOAD_RACK_STORE20_POS      = 0X29,//试管架仓20装载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_UNLOAD_RACK_STORE20_POS    = 0X2A,//试管架仓20卸载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_LOAD_RACK_STORE21_POS      = 0X2B,//试管架仓21装载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_UNLOAD_RACK_STORE21_POS    = 0X2C,//试管架仓21卸载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_LOAD_RACK_STORE22_POS      = 0X2D,//试管架仓22装载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_UNLOAD_RACK_STORE22_POS    = 0X2E,//试管架仓22卸载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_LOAD_RACK_STORE23_POS      = 0X2F,//试管架仓23装载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_UNLOAD_RACK_STORE23_POS    = 0X30,//试管架仓23卸载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_LOADC21_POS                = 0X31,//C21装载位置
    INDEX_SUB_PARAM_UPDOWN_MOTOR_UNLOADC21_POS              = 0X32,//C21卸载位置
}INDEX_SUB_PARAM_UPDOWN_MOTOR;

//顶杆电机坐标参数集合
typedef enum INDEX_SUB_PARAM_ROD_MOTOR
{
    INDEX_SUB_PARAM_ROD_MOTOR_RESET_CORRECT              = 0X00,//复位修正
    INDEX_SUB_PARAM_ROD_MOTOR_DIR_SWITCH_CORRECT         = 0X01,//换向修正
    INDEX_SUB_PARAM_ROD_MOTOR_IDLE_POS                   = 0X02,//空闲位置
    INDEX_SUB_PARAM_ROD_MOTOR_LOAD_RACK_STORE1_POS       = 0X03,//试管架仓1装载位置
    INDEX_SUB_PARAM_ROD_MOTOR_UNLOAD_RACK_STORE1_POS     = 0X04,//试管架仓1卸载位置
    INDEX_SUB_PARAM_ROD_MOTOR_LOAD_RACK_STORE2_POS       = 0X05,//试管架仓2装载位置
    INDEX_SUB_PARAM_ROD_MOTOR_UNLOAD_RACK_STORE2_POS     = 0X06,//试管架仓2卸载位置
    INDEX_SUB_PARAM_ROD_MOTOR_LOAD_RACK_STORE3_POS       = 0X07,//试管架仓3装载位置
    INDEX_SUB_PARAM_ROD_MOTOR_UNLOAD_RACK_STORE3_POS     = 0X08,//试管架仓3卸载位置
    INDEX_SUB_PARAM_ROD_MOTOR_LOAD_RACK_STORE4_POS       = 0X09,//试管架仓4装载位置
    INDEX_SUB_PARAM_ROD_MOTOR_UNLOAD_RACK_STORE4_POS     = 0X0A,//试管架仓4卸载位置
    INDEX_SUB_PARAM_ROD_MOTOR_LOAD_RACK_STORE5_POS       = 0X0B,//试管架仓5装载位置
    INDEX_SUB_PARAM_ROD_MOTOR_UNLOAD_RACK_STORE5_POS     = 0X0C,//试管架仓5卸载位置
    INDEX_SUB_PARAM_ROD_MOTOR_LOAD_RACK_STORE6_POS       = 0X0D,//试管架仓6装载位置
    INDEX_SUB_PARAM_ROD_MOTOR_UNLOAD_RACK_STORE6_POS     = 0X0E,//试管架仓6卸载位置
    INDEX_SUB_PARAM_ROD_MOTOR_LOAD_RACK_STORE7_POS       = 0X0F,//试管架仓7装载位置
    INDEX_SUB_PARAM_ROD_MOTOR_UNLOAD_RACK_STORE7_POS     = 0X10,//试管架仓7卸载位置
    INDEX_SUB_PARAM_ROD_MOTOR_LOAD_RACK_STORE8_POS       = 0X11,//试管架仓8装载位置
    INDEX_SUB_PARAM_ROD_MOTOR_UNLOAD_RACK_STORE8_POS     = 0X12,//试管架仓8卸载位置
    INDEX_SUB_PARAM_ROD_MOTOR_LOAD_RACK_STORE9_POS       = 0X13,//试管架仓9装载位置
    INDEX_SUB_PARAM_ROD_MOTOR_UNLOAD_RACK_STORE9_POS     = 0X14,//试管架仓9卸载位置
    INDEX_SUB_PARAM_ROD_MOTOR_LOAD_RACK_STORE10_POS      = 0X15,//试管架仓10装载位置
    INDEX_SUB_PARAM_ROD_MOTOR_UNLOAD_RACK_STORE10_POS    = 0X16,//试管架仓10卸载位置
    INDEX_SUB_PARAM_ROD_MOTOR_LOAD_RACK_STORE11_POS      = 0X17,//试管架仓11装载位置
    INDEX_SUB_PARAM_ROD_MOTOR_UNLOAD_RACK_STORE11_POS    = 0X18,//试管架仓11卸载位置
    INDEX_SUB_PARAM_ROD_MOTOR_LOAD_RACK_STORE12_POS      = 0X19,//试管架仓12装载位置
    INDEX_SUB_PARAM_ROD_MOTOR_UNLOAD_RACK_STORE12_POS    = 0X1A,//试管架仓12卸载位置
    INDEX_SUB_PARAM_ROD_MOTOR_LOAD_RACK_STORE13_POS      = 0X1B,//试管架仓13装载位置
    INDEX_SUB_PARAM_ROD_MOTOR_UNLOAD_RACK_STORE13_POS    = 0X1C,//试管架仓13卸载位置
    INDEX_SUB_PARAM_ROD_MOTOR_LOAD_RACK_STORE14_POS      = 0X1D,//试管架仓14装载位置
    INDEX_SUB_PARAM_ROD_MOTOR_UNLOAD_RACK_STORE14_POS    = 0X1E,//试管架仓14卸载位置
    INDEX_SUB_PARAM_ROD_MOTOR_LOAD_RACK_STORE15_POS      = 0X1F,//试管架仓15装载位置
    INDEX_SUB_PARAM_ROD_MOTOR_UNLOAD_RACK_STORE15_POS    = 0X20,//试管架仓15卸载位置
    INDEX_SUB_PARAM_ROD_MOTOR_LOAD_RACK_STORE16_POS      = 0X21,//试管架仓16装载位置
    INDEX_SUB_PARAM_ROD_MOTOR_UNLOAD_RACK_STORE16_POS    = 0X22,//试管架仓16卸载位置
    INDEX_SUB_PARAM_ROD_MOTOR_LOAD_RACK_STORE17_POS      = 0X23,//试管架仓17装载位置
    INDEX_SUB_PARAM_ROD_MOTOR_UNLOAD_RACK_STORE17_POS    = 0X24,//试管架仓17卸载位置
    INDEX_SUB_PARAM_ROD_MOTOR_LOAD_RACK_STORE18_POS      = 0X25,//试管架仓18装载位置
    INDEX_SUB_PARAM_ROD_MOTOR_UNLOAD_RACK_STORE18_POS    = 0X26,//试管架仓18卸载位置
    INDEX_SUB_PARAM_ROD_MOTOR_LOAD_RACK_STORE19_POS      = 0X27,//试管架仓19装载位置
    INDEX_SUB_PARAM_ROD_MOTOR_UNLOAD_RACK_STORE19_POS    = 0X28,//试管架仓19卸载位置
    INDEX_SUB_PARAM_ROD_MOTOR_LOAD_RACK_STORE20_POS      = 0X29,//试管架仓20装载位置
    INDEX_SUB_PARAM_ROD_MOTOR_UNLOAD_RACK_STORE20_POS    = 0X2A,//试管架仓20卸载位置
    INDEX_SUB_PARAM_ROD_MOTOR_LOAD_RACK_STORE21_POS      = 0X2B,//试管架仓21装载位置
    INDEX_SUB_PARAM_ROD_MOTOR_UNLOAD_RACK_STORE21_POS    = 0X2C,//试管架仓21卸载位置
    INDEX_SUB_PARAM_ROD_MOTOR_LOAD_RACK_STORE22_POS      = 0X2D,//试管架仓22装载位置
    INDEX_SUB_PARAM_ROD_MOTOR_UNLOAD_RACK_STORE22_POS    = 0X2E,//试管架仓22卸载位置
    INDEX_SUB_PARAM_ROD_MOTOR_LOAD_RACK_STORE23_POS      = 0X2F,//试管架仓23装载位置
    INDEX_SUB_PARAM_ROD_MOTOR_UNLOAD_RACK_STORE23_POS    = 0X30,//试管架仓23卸载位置
    INDEX_SUB_PARAM_ROD_MOTOR_LOADC21_POS                = 0X31,//C21装载位置
    INDEX_SUB_PARAM_ROD_MOTOR_UNLOADC21_POS              = 0X32,//C21卸载位置
}INDEX_SUB_PARAM_ROD_MOTOR;

//皮带电机坐标参数集合
typedef enum INDEX_SUB_PARAM_BELT_MOTOR
{
    INDEX_SUB_PARAM_BELT_MOTOR_RESET_CORRECT              = 0X00,//复位修正
    INDEX_SUB_PARAM_BELT_MOTOR_DIR_SWITCH_CORRECT         = 0X01,//换向修正
    INDEX_SUB_PARAM_BELT_MOTOR_IDLE_POS                   = 0X02,//空闲位置
    INDEX_SUB_PARAM_BELT_MOTOR_LOAD_RACK_STORE1_POS       = 0X03,//试管架仓1装载位置
    INDEX_SUB_PARAM_BELT_MOTOR_UNLOAD_RACK_STORE1_POS     = 0X04,//试管架仓1卸载位置
    INDEX_SUB_PARAM_BELT_MOTOR_LOAD_RACK_STORE2_POS       = 0X05,//试管架仓2装载位置
    INDEX_SUB_PARAM_BELT_MOTOR_UNLOAD_RACK_STORE2_POS     = 0X06,//试管架仓2卸载位置
    INDEX_SUB_PARAM_BELT_MOTOR_LOAD_RACK_STORE3_POS       = 0X07,//试管架仓3装载位置
    INDEX_SUB_PARAM_BELT_MOTOR_UNLOAD_RACK_STORE3_POS     = 0X08,//试管架仓3卸载位置
    INDEX_SUB_PARAM_BELT_MOTOR_LOAD_RACK_STORE4_POS       = 0X09,//试管架仓4装载位置
    INDEX_SUB_PARAM_BELT_MOTOR_UNLOAD_RACK_STORE4_POS     = 0X0A,//试管架仓4卸载位置
    INDEX_SUB_PARAM_BELT_MOTOR_LOAD_RACK_STORE5_POS       = 0X0B,//试管架仓5装载位置
    INDEX_SUB_PARAM_BELT_MOTOR_UNLOAD_RACK_STORE5_POS     = 0X0C,//试管架仓5卸载位置
    INDEX_SUB_PARAM_BELT_MOTOR_LOAD_RACK_STORE6_POS       = 0X0D,//试管架仓6装载位置
    INDEX_SUB_PARAM_BELT_MOTOR_UNLOAD_RACK_STORE6_POS     = 0X0E,//试管架仓6卸载位置
    INDEX_SUB_PARAM_BELT_MOTOR_LOAD_RACK_STORE7_POS       = 0X0F,//试管架仓7装载位置
    INDEX_SUB_PARAM_BELT_MOTOR_UNLOAD_RACK_STORE7_POS     = 0X10,//试管架仓7卸载位置
    INDEX_SUB_PARAM_BELT_MOTOR_LOAD_RACK_STORE8_POS       = 0X11,//试管架仓8装载位置
    INDEX_SUB_PARAM_BELT_MOTOR_UNLOAD_RACK_STORE8_POS     = 0X12,//试管架仓8卸载位置
    INDEX_SUB_PARAM_BELT_MOTOR_LOAD_RACK_STORE9_POS       = 0X13,//试管架仓9装载位置
    INDEX_SUB_PARAM_BELT_MOTOR_UNLOAD_RACK_STORE9_POS     = 0X14,//试管架仓9卸载位置
    INDEX_SUB_PARAM_BELT_MOTOR_LOAD_RACK_STORE10_POS      = 0X15,//试管架仓10装载位置
    INDEX_SUB_PARAM_BELT_MOTOR_UNLOAD_RACK_STORE10_POS    = 0X16,//试管架仓10卸载位置
    INDEX_SUB_PARAM_BELT_MOTOR_LOAD_RACK_STORE11_POS      = 0X17,//试管架仓11装载位置
    INDEX_SUB_PARAM_BELT_MOTOR_UNLOAD_RACK_STORE11_POS    = 0X18,//试管架仓11卸载位置
    INDEX_SUB_PARAM_BELT_MOTOR_LOAD_RACK_STORE12_POS      = 0X19,//试管架仓12装载位置
    INDEX_SUB_PARAM_BELT_MOTOR_UNLOAD_RACK_STORE12_POS    = 0X1A,//试管架仓12卸载位置
    INDEX_SUB_PARAM_BELT_MOTOR_LOAD_RACK_STORE13_POS      = 0X1B,//试管架仓13装载位置
    INDEX_SUB_PARAM_BELT_MOTOR_UNLOAD_RACK_STORE13_POS    = 0X1C,//试管架仓13卸载位置
    INDEX_SUB_PARAM_BELT_MOTOR_LOAD_RACK_STORE14_POS      = 0X1D,//试管架仓14装载位置
    INDEX_SUB_PARAM_BELT_MOTOR_UNLOAD_RACK_STORE14_POS    = 0X1E,//试管架仓14卸载位置
    INDEX_SUB_PARAM_BELT_MOTOR_LOAD_RACK_STORE15_POS      = 0X1F,//试管架仓15装载位置
    INDEX_SUB_PARAM_BELT_MOTOR_UNLOAD_RACK_STORE15_POS    = 0X20,//试管架仓15卸载位置
    INDEX_SUB_PARAM_BELT_MOTOR_LOAD_RACK_STORE16_POS      = 0X21,//试管架仓16装载位置
    INDEX_SUB_PARAM_BELT_MOTOR_UNLOAD_RACK_STORE16_POS    = 0X22,//试管架仓16卸载位置
    INDEX_SUB_PARAM_BELT_MOTOR_LOAD_RACK_STORE17_POS      = 0X23,//试管架仓17装载位置
    INDEX_SUB_PARAM_BELT_MOTOR_UNLOAD_RACK_STORE17_POS    = 0X24,//试管架仓17卸载位置
    INDEX_SUB_PARAM_BELT_MOTOR_LOAD_RACK_STORE18_POS      = 0X25,//试管架仓18装载位置
    INDEX_SUB_PARAM_BELT_MOTOR_UNLOAD_RACK_STORE18_POS    = 0X26,//试管架仓18卸载位置
    INDEX_SUB_PARAM_BELT_MOTOR_LOAD_RACK_STORE19_POS      = 0X27,//试管架仓19装载位置
    INDEX_SUB_PARAM_BELT_MOTOR_UNLOAD_RACK_STORE19_POS    = 0X28,//试管架仓19卸载位置
    INDEX_SUB_PARAM_BELT_MOTOR_LOAD_RACK_STORE20_POS      = 0X29,//试管架仓20装载位置
    INDEX_SUB_PARAM_BELT_MOTOR_UNLOAD_RACK_STORE20_POS    = 0X2A,//试管架仓20卸载位置
    INDEX_SUB_PARAM_BELT_MOTOR_LOAD_RACK_STORE21_POS      = 0X2B,//试管架仓21装载位置
    INDEX_SUB_PARAM_BELT_MOTOR_UNLOAD_RACK_STORE21_POS    = 0X2C,//试管架仓21卸载位置
    INDEX_SUB_PARAM_BELT_MOTOR_LOAD_RACK_STORE22_POS      = 0X2D,//试管架仓22装载位置
    INDEX_SUB_PARAM_BELT_MOTOR_UNLOAD_RACK_STORE22_POS    = 0X2E,//试管架仓22卸载位置
    INDEX_SUB_PARAM_BELT_MOTOR_LOAD_RACK_STORE23_POS      = 0X2F,//试管架仓23装载位置
    INDEX_SUB_PARAM_BELT_MOTOR_UNLOAD_RACK_STORE23_POS    = 0X30,//试管架仓23卸载位置
    INDEX_SUB_PARAM_BELT_MOTOR_LOADC21_POS                = 0X31,//C21装载位置
    INDEX_SUB_PARAM_BELT_MOTOR_UNLOADC21_POS              = 0X32,//C21卸载位置
    INDEX_SUB_PARAM_BELT_MOTOR_BAR_SCAN_START_POS         = 0X33,//扫码起始位置
    INDEX_SUB_PARAM_BELT_MOTOR_BAR_SCAN_END_POS           = 0X34,//扫码结束位置
    INDEX_SUB_PARAM_BELT_MOTOR_TUBE1_SCAN_POS             = 0X35,//试管扫码点1
    INDEX_SUB_PARAM_BELT_MOTOR_TUBE2_SCAN_POS             = 0X36,//试管扫码点2
    INDEX_SUB_PARAM_BELT_MOTOR_TUBE3_SCAN_POS             = 0X37,//试管扫码点3
    INDEX_SUB_PARAM_BELT_MOTOR_TUBE4_SCAN_POS             = 0X38,//试管扫码点4
    INDEX_SUB_PARAM_BELT_MOTOR_TUBE5_SCAN_POS             = 0X39,//试管扫码点5
    INDEX_SUB_PARAM_BELT_MOTOR_TUBE6_SCAN_POS             = 0X3A,//试管扫码点6
    INDEX_SUB_PARAM_BELT_MOTOR_TUBE7_SCAN_POS             = 0X3B,//试管扫码点7
    INDEX_SUB_PARAM_BELT_MOTOR_TUBE8_SCAN_POS             = 0X3C,//试管扫码点8
    INDEX_SUB_PARAM_BELT_MOTOR_TUBE9_SCAN_POS             = 0X3D,//试管扫码点9
    INDEX_SUB_PARAM_BELT_MOTOR_TUBE10_SCAN_POS            = 0X3E,//试管扫码点10
    INDEX_SUB_PARAM_BELT_MOTOR_ADJUST_START_POS           = 0X3F,//校准起始点
    INDEX_SUB_PARAM_BELT_MOTOR_ADJUST_OVER_POS            = 0X40,//校准结束点
}INDEX_SUB_PARAM_BELT_MOTOR;


//辅助参数参数集合
typedef enum INDEX_SUB_PARAM_UTIL
{
    INDEX_SUB_PARAM_UTIL_SCAN_MODE                      = 0X00,//扫码模式
}INDEX_SUB_PARAM_UTIL;

//初始化系统参数
void SysParamInit(void);

//写入参数
ERROR_SUB SysParamWriteSingle(INDEX_MAIN_SYS_PARAM mainIndex,uint8_t subIndex,int32_t paramWrite);

//读取参数
ERROR_SUB SysParamReadSingle(INDEX_MAIN_SYS_PARAM mainIndex,uint8_t subIndex,int32_t* paramRead);


#endif








