/*********************************************************************************************** 
** Author        : DengXiaoJun(邓小俊)
** Date          : 2023-02-11 14:38:46 +0800
** Description   : When I Has Time ,I Will Write Description Below:
** ModifyRecord1 :    
** ModifyRecord2 :    
** LastEditors   : DengXiaoJun(邓小俊)
** LastEditTime  : 2023-11-21 09:19:09 +0800
************************************************************************************************/ 
#ifndef __MCU_ADC_UNIVERSAL_H_
#define __MCU_ADC_UNIVERSAL_H_
#include "CoreUtil.h"
#include "MCU_PIN.h"

//规则组序号
typedef enum MCU_ADC_REGULAR_RANK
{
    MCU_ADC_REGULAR_RANK_1  = 0X01U,
    MCU_ADC_REGULAR_RANK_2  = 0X02U,
    MCU_ADC_REGULAR_RANK_3  = 0X03U,
    MCU_ADC_REGULAR_RANK_4  = 0X04U,
    MCU_ADC_REGULAR_RANK_5  = 0X05U,
    MCU_ADC_REGULAR_RANK_6  = 0X06U,
    MCU_ADC_REGULAR_RANK_7  = 0X07U,
    MCU_ADC_REGULAR_RANK_8  = 0X08U,
    MCU_ADC_REGULAR_RANK_9  = 0X09U,
    MCU_ADC_REGULAR_RANK_10 = 0X0AU,
    MCU_ADC_REGULAR_RANK_11 = 0X0BU,
    MCU_ADC_REGULAR_RANK_12 = 0X0CU,
    MCU_ADC_REGULAR_RANK_13 = 0X0DU,
    MCU_ADC_REGULAR_RANK_14 = 0X0EU,
    MCU_ADC_REGULAR_RANK_15 = 0X0FU,
    MCU_ADC_REGULAR_RANK_16 = 0X10U,
}MCU_ADC_REGULAR_RANK;

//规则组通道
typedef enum MCU_ADC_CHANNEL
{
    MCU_ADC_CHANNEL_0  = ADC_CHANNEL_0 ,
    MCU_ADC_CHANNEL_1  = ADC_CHANNEL_1 ,
    MCU_ADC_CHANNEL_2  = ADC_CHANNEL_2 ,
    MCU_ADC_CHANNEL_3  = ADC_CHANNEL_3 ,
    MCU_ADC_CHANNEL_4  = ADC_CHANNEL_4 ,
    MCU_ADC_CHANNEL_5  = ADC_CHANNEL_5 ,
    MCU_ADC_CHANNEL_6  = ADC_CHANNEL_6 ,
    MCU_ADC_CHANNEL_7  = ADC_CHANNEL_7 ,
    MCU_ADC_CHANNEL_8  = ADC_CHANNEL_8 ,
    MCU_ADC_CHANNEL_9  = ADC_CHANNEL_9 ,
    MCU_ADC_CHANNEL_10 = ADC_CHANNEL_10,
    MCU_ADC_CHANNEL_11 = ADC_CHANNEL_11,
    MCU_ADC_CHANNEL_12 = ADC_CHANNEL_12,
    MCU_ADC_CHANNEL_13 = ADC_CHANNEL_13,
    MCU_ADC_CHANNEL_14 = ADC_CHANNEL_14,
    MCU_ADC_CHANNEL_15 = ADC_CHANNEL_15,
    MCU_ADC_CHANNEL_16 = ADC_CHANNEL_16,
    MCU_ADC_CHANNEL_17 = ADC_CHANNEL_17,
    MCU_ADC_CHANNEL_18 = ADC_CHANNEL_18,
    MCU_ADC_CHANNEL_TEMPSENSOR = ADC_CHANNEL_TEMPSENSOR,
    MCU_ADC_CHANNEL_VREFINT    = ADC_CHANNEL_VREFINT   ,
}MCU_ADC_CHANNEL;

//采样周期
typedef enum MCU_ADC_SAMPLE
{
    MCU_ADC_SAMPLE_3CYCLES   = ADC_SAMPLETIME_3CYCLES  ,
    MCU_ADC_SAMPLE_15CYCLES  = ADC_SAMPLETIME_15CYCLES ,
    MCU_ADC_SAMPLE_28CYCLES  = ADC_SAMPLETIME_28CYCLES ,
    MCU_ADC_SAMPLE_56CYCLES  = ADC_SAMPLETIME_56CYCLES ,
    MCU_ADC_SAMPLE_84CYCLES  = ADC_SAMPLETIME_84CYCLES ,
    MCU_ADC_SAMPLE_112CYCLES = ADC_SAMPLETIME_112CYCLES,
    MCU_ADC_SAMPLE_144CYCLES = ADC_SAMPLETIME_144CYCLES,
    MCU_ADC_SAMPLE_480CYCLES = ADC_SAMPLETIME_480CYCLES,
}MCU_ADC_SAMPLE;

typedef struct MCU_ADC_CHANNEL_CONFIG
{
    MCU_PIN adcChannelPin;
    MCU_ADC_REGULAR_RANK rankSet;
    MCU_ADC_CHANNEL channel;
    MCU_ADC_SAMPLE sampleTime;
}MCU_ADC_CHANNEL_CONFIG;



#endif



