/*********************************************************************************************** 
** Author        : DengXiaoJun(邓小俊)
** Date          : 2023-04-26 10:18:50 +0800
** Description   : When I Has Time ,I Will Write Description Below:
** ModifyRecord1 :    
** ModifyRecord2 :    
** LastEditors   : DengXiaoJun(邓小俊)
** LastEditTime  : 2023-04-26 10:18:59 +0800
************************************************************************************************/ 
#ifndef __BOARD_FPGA_REG_H_
#define __BOARD_FPGA_REG_H_
#include "BoardFPGA_Macro.h"

//写入基础地址
typedef enum FPGA_REG_WRITE_BASE
{
    FPGA_REG_WRITE_BASE_ADDR_LOW     = 0XFFFB,//写入地址,低字节
    FPGA_REG_WRITE_BASE_ADDR_HIGH    = 0XFFFC,//写入地址,高字节
    FPGA_REG_WRITE_BASE_DATA_LOW     = 0XFFFD,//写入数据,低字节
    FPGA_REG_WRITE_BASE_DATA_HIGH    = 0XFFFE,//写入数据,高字节
}FPGA_REG_WRITE_BASE;

//读取地址
typedef enum FPGA_REG_READ_ADDR
{
    FPGA_REG_READ_ADDR_VERSION                  = 0X0001,//软件版本
    FPGA_REG_READ_ADDR_STEP_MOTOR_INT           = 0X0003,//步进电机中断寄存器
    FPGA_REG_READ_ADDR_CHIP_ID                  = 0XFFF1,//识别ID
    FPGA_REG_READ_ADDR_CHIP_BUSY                = 0XFFF2,//写入忙状态
    //PORT_IN_GROUP_A   
    FPGA_REG_READ_ADDR_PORT_IN_GROUP_A_MODE     = 0X0021,//输入模式
    FPGA_REG_READ_ADDR_PORT_IN_GROUP_A_STATE    = 0X0023,//输入状态
    //PORT_IN_GROUP_B   
    FPGA_REG_READ_ADDR_PORT_IN_GROUP_B_MODE     = 0X0031,//输入模式
    FPGA_REG_READ_ADDR_PORT_IN_GROUP_B_STATE    = 0X0033,//输入状态
    //PORT_IN_GROUP_C   
    FPGA_REG_READ_ADDR_PORT_IN_GROUP_C_MODE     = 0X0041,//输入模式
    FPGA_REG_READ_ADDR_PORT_IN_GROUP_C_STATE    = 0X0043,//输入状态
    //PORT_IN_GROUP_D   
    FPGA_REG_READ_ADDR_PORT_IN_GROUP_D_MODE     = 0X0051,//输入模式
    FPGA_REG_READ_ADDR_PORT_IN_GROUP_D_STATE    = 0X0053,//输入状态
    //PORT_OUT_GROUP_A  
    FPGA_REG_READ_ADDR_PORT_OUT_GROUP_A_MODE    = 0X0101,//输出模式
    FPGA_REG_READ_ADDR_PORT_OUT_GROUP_A_SET     = 0X0103,//输出状态
    FPGA_REG_READ_ADDR_PORT_OUT_GROUP_A_REAL    = 0X0105,//实际输出值
    //PORT_OUT_GROUP_B
    FPGA_REG_READ_ADDR_PORT_OUT_GROUP_B_MODE    = 0X0111,//输出模式
    FPGA_REG_READ_ADDR_PORT_OUT_GROUP_B_SET     = 0X0113,//输出状态
    FPGA_REG_READ_ADDR_PORT_OUT_GROUP_B_REAL    = 0X0115,//实际输出值
    //PORT_OUT_GROUP_C  
    FPGA_REG_READ_ADDR_PORT_OUT_GROUP_C_MODE    = 0X0121,//输出模式
    FPGA_REG_READ_ADDR_PORT_OUT_GROUP_C_SET     = 0X0123,//输出状态
    FPGA_REG_READ_ADDR_PORT_OUT_GROUP_C_REAL    = 0X0125,//实际输出值
    //PORT_OUT_GROUP_D  
    FPGA_REG_READ_ADDR_PORT_OUT_GROUP_D_MODE    = 0X0131,//输出模式
    FPGA_REG_READ_ADDR_PORT_OUT_GROUP_D_SET     = 0X0133,//输出状态
    FPGA_REG_READ_ADDR_PORT_OUT_GROUP_D_REAL    = 0X0135,//实际输出值
    //步进电机基础读寄存器地址  
    FPGA_REG_READ_ADDR_STEP_MOTOR1_BASE         = 0X0200,//步进电机1基础地址
    FPGA_REG_READ_ADDR_STEP_MOTOR2_BASE         = 0X0300,//步进电机2基础地址
    FPGA_REG_READ_ADDR_STEP_MOTOR3_BASE         = 0X0400,//步进电机3基础地址
    FPGA_REG_READ_ADDR_STEP_MOTOR4_BASE         = 0X0500,//步进电机4基础地址
    FPGA_REG_READ_ADDR_STEP_MOTOR5_BASE         = 0X0600,//步进电机5基础地址
    FPGA_REG_READ_ADDR_STEP_MOTOR6_BASE         = 0X0700,//步进电机6基础地址
    FPGA_REG_READ_ADDR_STEP_MOTOR7_BASE         = 0X0800,//步进电机7基础地址
    FPGA_REG_READ_ADDR_STEP_MOTOR8_BASE         = 0X0900,//步进电机8基础地址
    FPGA_REG_READ_ADDR_STEP_MOTOR9_BASE         = 0X0A00,//步进电机9基础地址
    FPGA_REG_READ_ADDR_STEP_MOTOR10_BASE        = 0X0B00,//步进电机10基础地址
    FPGA_REG_READ_ADDR_STEP_MOTOR11_BASE        = 0X0C00,//步进电机11基础地址
    FPGA_REG_READ_ADDR_STEP_MOTOR12_BASE        = 0X0D00,//步进电机12基础地址
    FPGA_REG_READ_ADDR_STEP_MOTOR13_BASE        = 0X0E00,//步进电机13基础地址
    FPGA_REG_READ_ADDR_STEP_MOTOR14_BASE        = 0X0F00,//步进电机14基础地址
    FPGA_REG_READ_ADDR_STEP_MOTOR15_BASE        = 0X1000,//步进电机15基础地址
    FPGA_REG_READ_ADDR_STEP_MOTOR16_BASE        = 0X1100,//步进电机16基础地址
    //步进电机读寄存器偏移地址
    FPGA_REG_READ_ADDR_STEP_MOTOR_CONFIG        = 0X0001,//配置寄存器
    FPGA_REG_READ_ADDR_STEP_MOTOR_PARAM1        = 0X000B,//参数寄存器
    FPGA_REG_READ_ADDR_STEP_MOTOR_PARAM2        = 0X000D,//
    FPGA_REG_READ_ADDR_STEP_MOTOR_PARAM3        = 0X000F,//
    FPGA_REG_READ_ADDR_STEP_MOTOR_PARAM4        = 0X0011,//
    FPGA_REG_READ_ADDR_STEP_MOTOR_PARAM5        = 0X0013,//
    FPGA_REG_READ_ADDR_STEP_MOTOR_CONTROL       = 0X0031,//控制寄存器
    FPGA_REG_READ_ADDR_STEP_MOTOR_STATE1        = 0X0051,//状态寄存器
    FPGA_REG_READ_ADDR_STEP_MOTOR_STATE2        = 0X0053,//
    FPGA_REG_READ_ADDR_STEP_MOTOR_STATE3        = 0X0055,//
    FPGA_REG_READ_ADDR_STEP_MOTOR_STATE4        = 0X0057,//
    FPGA_REG_READ_ADDR_STEP_MOTOR_STATE5        = 0X0059,//
    FPGA_REG_READ_ADDR_STEP_MOTOR_SPD_TAB_ELEM  = 0X005B,//速度表元素寄存器
    FPGA_REG_READ_ADDR_STEP_MOTOR_STP_TAB_ELEM  = 0X005D,//步数表元素寄存器
}FPGA_REG_READ_ADDR;


//写入地址
typedef enum FPGA_REG_WRITE_ADDR
{
    //PORT_OUT_GROUP_A
    FPGA_REG_WRITE_ADDR_PORT_OUT_GROUP_A_MODE           = 0X00000000,//端口输出模式
    FPGA_REG_WRITE_ADDR_PORT_OUT_GROUP_A_STATE          = 0X00000001,//端口输出状态
    //PORT_OUT_GROUP_B
    FPGA_REG_WRITE_ADDR_PORT_OUT_GROUP_B_MODE           = 0X00000010,//端口输出模式
    FPGA_REG_WRITE_ADDR_PORT_OUT_GROUP_B_STATE          = 0X00000011,//端口输出状态
    //PORT_OUT_GROUP_C
    FPGA_REG_WRITE_ADDR_PORT_OUT_GROUP_C_MODE           = 0X00000020,//端口输出模式
    FPGA_REG_WRITE_ADDR_PORT_OUT_GROUP_C_STATE          = 0X00000021,//端口输出状态
    //PORT_OUT_GROUP_D
    FPGA_REG_WRITE_ADDR_PORT_OUT_GROUP_D_MODE           = 0X00000030,//端口输出模式
    FPGA_REG_WRITE_ADDR_PORT_OUT_GROUP_D_STATE          = 0X00000031,//端口输出状态
    //PORT_IN_GROUP_A       
    FPGA_REG_WRITE_ADDR_PORT_IN_GROUP_A_MODE            = 0x00000100,//端口输入模式
    //PORT_IN_GROUP_B       
    FPGA_REG_WRITE_ADDR_PORT_IN_GROUP_B_MODE            = 0x00000110,//端口输入模式
    //PORT_IN_GROUP_C       
    FPGA_REG_WRITE_ADDR_PORT_IN_GROUP_C_MODE            = 0x00000120,//端口输入模式
    //PORT_IN_GROUP_D       
    FPGA_REG_WRITE_ADDR_PORT_IN_GROUP_D_MODE            = 0x00000130,//端口输入模式
    //步进电机写入基础地址      
    FPGA_REG_WRITE_ADDR_STEP_MOTOR1_BASE_ADDR           = 0X00010000,//步进电机1写入基准地址
    FPGA_REG_WRITE_ADDR_STEP_MOTOR2_BASE_ADDR           = 0X00020000,//步进电机2写入基准地址
    FPGA_REG_WRITE_ADDR_STEP_MOTOR3_BASE_ADDR           = 0X00030000,//步进电机3写入基准地址
    FPGA_REG_WRITE_ADDR_STEP_MOTOR4_BASE_ADDR           = 0X00040000,//步进电机4写入基准地址
    FPGA_REG_WRITE_ADDR_STEP_MOTOR5_BASE_ADDR           = 0X00050000,//步进电机5写入基准地址
    FPGA_REG_WRITE_ADDR_STEP_MOTOR6_BASE_ADDR           = 0X00060000,//步进电机6写入基准地址
    FPGA_REG_WRITE_ADDR_STEP_MOTOR7_BASE_ADDR           = 0X00070000,//步进电机7写入基准地址
    FPGA_REG_WRITE_ADDR_STEP_MOTOR8_BASE_ADDR           = 0X00080000,//步进电机8写入基准地址
    FPGA_REG_WRITE_ADDR_STEP_MOTOR9_BASE_ADDR           = 0X00090000,//步进电机9写入基准地址
    FPGA_REG_WRITE_ADDR_STEP_MOTOR10_BASE_ADDR          = 0X000A0000,//步进电机10写入基准地址
    FPGA_REG_WRITE_ADDR_STEP_MOTOR11_BASE_ADDR          = 0X000B0000,//步进电机11写入基准地址
    FPGA_REG_WRITE_ADDR_STEP_MOTOR12_BASE_ADDR          = 0X000C0000,//步进电机12写入基准地址
    FPGA_REG_WRITE_ADDR_STEP_MOTOR13_BASE_ADDR          = 0X000D0000,//步进电机13写入基准地址
    FPGA_REG_WRITE_ADDR_STEP_MOTOR14_BASE_ADDR          = 0X000E0000,//步进电机14写入基准地址
    FPGA_REG_WRITE_ADDR_STEP_MOTOR15_BASE_ADDR          = 0X000F0000,//步进电机15写入基准地址
    FPGA_REG_WRITE_ADDR_STEP_MOTOR16_BASE_ADDR          = 0X00100000,//步进电机16写入基准地址
    //步进电机写寄存器偏移地址
    FPGA_REG_WRITE_ADDR_STEP_MOTOR_CONFIG               = 0X00000000,//配置寄存器
    FPGA_REG_WRITE_ADDR_STEP_MOTOR_PARAM1               = 0X00000001,//参数寄存器
    FPGA_REG_WRITE_ADDR_STEP_MOTOR_PARAM2               = 0X00000002,
    FPGA_REG_WRITE_ADDR_STEP_MOTOR_PARAM3               = 0X00000003,
    FPGA_REG_WRITE_ADDR_STEP_MOTOR_PARAM4               = 0X00000004,
    FPGA_REG_WRITE_ADDR_STEP_MOTOR_PARAM5               = 0X00000005,
    FPGA_REG_WRITE_ADDR_STEP_MOTOR_CONTROL              = 0X00000006,//控制寄存器
    FPGA_REG_WRITE_ADDR_STEP_MOTOR_SPD_TAB_ELEM_READ    = 0X00000010,//速度表元素读取寄存器
    FPGA_REG_WRITE_ADDR_STEP_MOTOR_STP_TAB_ELEM_READ    = 0X00000011,//步数表元素读取寄存器
    FPGA_REG_WRITE_ADDR_STEP_MOTOR_SPD_TAB_ELEM_WRITE   = 0X00000020,//速度表元素写入寄存器
    FPGA_REG_WRITE_ADDR_STEP_MOTOR_STP_TAB_ELEM_WRITE   = 0X00008000,//步数表元素写入寄存器
}FPGA_REG_WRITE_ADDR;


#endif



